# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: CI Pipeline

# Trigger the workflow on push or pull request
on: push

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [13.x]

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install Dependencies
        uses: bahmutov/npm-install@v1
      - name: Check Format
        run: |
          git fetch origin
          [[ "$GITHUB_REF" =~ "refs/heads/master" ]] && export BASE_SHA="origin/master~1" ||  export BASE_SHA="origin/master"
          yarn format:check --base="$BASE_SHA"
      - name: Lint Files
        run: |
          git fetch origin
          [[ "$GITHUB_REF" =~ "refs/heads/master" ]] && export BASE_SHA="origin/master~1" ||  export BASE_SHA="origin/master"
          yarn affected:lint --base="$BASE_SHA"
      - name: Run Unit Tests
        run: |
          git fetch origin
          [[ "$GITHUB_REF" =~ "refs/heads/master" ]] && export BASE_SHA="origin/master~1" ||  export BASE_SHA="origin/master"
          yarn affected:test --base="$BASE_SHA"
      - name: Run E2E Tests
        run: |
          git fetch origin
          [[ "$GITHUB_REF" =~ "refs/heads/master" ]] && export BASE_SHA="origin/master~1" ||  export BASE_SHA="origin/master"
          yarn affected:e2e --base="$BASE_SHA"
      - name: Build Packages & Apps
        run: |
          git fetch origin
          [[ "$GITHUB_REF" =~ "refs/heads/master" ]] && export BASE_SHA="origin/master~1" ||  export BASE_SHA="origin/master"
          yarn affected:build --base="$BASE_SHA"
      - name: Build Storybook
        run: |
          yarn nx run ui-header:build-storybook
      - name: Deploy Storybook
        id: deploy
        uses: Azure/static-web-apps-deploy@v0.0.1-preview
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_KIND_MEADOW_01FCA4303 }}
          repo_token: ${{ secrets.GITHUB_TOKEN }} # Used for Github integrations (i.e. PR comments)
          action: "upload"
          ###### Repository/Build Configurations - These values can be configured to match you app requirements. ######
          # For more information regarding Static Web App workflow configurations, please visit: https://aka.ms/swaworkflowconfig
          app_location: "/" # App source code path
          api_location: "" # Api source code path - optional
          app_artifact_location: "dist/storybook/ui-header" # Built app content directory - optional
          ###### End of Repository/Build Configurations ######    
