# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: CI Pipeline

# Trigger the workflow on push or pull request
on: push

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [13.x]

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install Dependencies
        uses: bahmutov/npm-install@v1
      - name: Check Format
        run: |
          git fetch origin
          [[ "$GITHUB_REF" =~ "refs/heads/master" ]] && export BASE_SHA="origin/master~1" ||  export BASE_SHA="origin/master"
          yarn format:check --base="$BASE_SHA"
      - name: Lint Files
        run: |
          git fetch origin
          [[ "$GITHUB_REF" =~ "refs/heads/master" ]] && export BASE_SHA="origin/master~1" ||  export BASE_SHA="origin/master"
          yarn affected:lint --base="$BASE_SHA"
      - name: Run Unit Tests
        run: |
          git fetch origin
          [[ "$GITHUB_REF" =~ "refs/heads/master" ]] && export BASE_SHA="origin/master~1" ||  export BASE_SHA="origin/master"
          yarn affected:test --base="$BASE_SHA"
      - name: Run E2E Tests
        run: |
          git fetch origin
          [[ "$GITHUB_REF" =~ "refs/heads/master" ]] && export BASE_SHA="origin/master~1" ||  export BASE_SHA="origin/master"
          yarn affected:e2e --base="$BASE_SHA"
      - name: Build Packages & Apps
        run: |
          git fetch origin
          [[ "$GITHUB_REF" =~ "refs/heads/master" ]] && export BASE_SHA="origin/master~1" ||  export BASE_SHA="origin/master"
          yarn affected:build --base="$BASE_SHA"
      - name: Build Storybook
        run: |
          yarn nx run ui-header:build-storybook
